import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e0e4d9",
        "on-surface-variant": "#41493c",
        "on-primary-fixed-variant": "#035300",
        "on-secondary-fixed-variant": "#004e5e",
        "error-container": "#ffdad6",
        "outline-variant": "#c0c9b8",
        "surface-tint": "#246c1a",
        "primary-container": "#3c842f",
        "primary-fixed": "#a8f692",
        "inverse-primary": "#8dd979",
        "surface-container": "#ebefe4",
        primary: "#216a17",
        tertiary: "#9a3768",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-container": "#006074",
        background: "#f7fbef",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f1f5ea",
        "on-primary-container": "#f8ffef",
        "on-tertiary": "#ffffff",
        "secondary-container": "#68defe",
        "tertiary-fixed": "#ffd9e5",
        "surface-bright": "#f7fbef",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#5ed5f5",
        "surface-container-high": "#e6eade",
        "inverse-surface": "#2d322a",
        "surface-container-highest": "#e0e4d9",
        "tertiary-fixed-dim": "#ffb0cf",
        "secondary-fixed": "#b0ecff",
        "on-tertiary-fixed-variant": "#7f2152",
        "on-background": "#181d16",
        error: "#ba1a1a",
        surface: "#f7fbef",
        "on-primary-fixed": "#012200",
        secondary: "#00687c",
        "on-error-container": "#93000a",
        "surface-dim": "#d7dcd1",
        "primary-fixed-dim": "#8dd979",
        "inverse-on-surface": "#eef2e7",
        outline: "#717a6b",
        "on-surface": "#181d16",
        "on-tertiary-container": "#fffbff",
        "tertiary-container": "#b95081",
        "on-tertiary-fixed": "#3d0023",
        "on-secondary-fixed": "#001f27",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
