import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import "material-symbols";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={manrope.variable}>
      <body className="bg-surface text-on-background font-body h-screen overflow-hidden flex items-center justify-center">
        {children}
        {/* <!-- Background Decoration for Entire Page --> */}
        <div className="fixed top-0 left-0 w-full h-full -z-10 pointer-events-none">
          <div className="absolute top-[10%] left-[5%] w-[400px] h-[400px] bg-primary-fixed/30 rounded-full blur-[120px]"></div>
          <div className="absolute bottom-[10%] right-[5%] w-[500px] h-[500px] bg-secondary-fixed/20 rounded-full blur-[150px]"></div>
        </div>
      </body>
    </html>
  );
}
