import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import "material-symbols";
import { Providers } from "@/providers/Provider";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={manrope.variable}>
      <body className="bg-surface text-on-background font-body flex items-center justify-center">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
